default:
  image: "archlinux:latest"
  tags:
    - secure-kvm
    - secure-virtualbox

before_script:
  - pacman -Syu --needed --noconfirm qemu-headless virtualbox packer

packer:
  script:
    packer build -parallel-builds=1 -var 'headless=true' -var 'write_zeroes=yes' -except=vmware-iso local.json
